[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'kana/vim-submode'


[[plugins]]
repo = 'kana/vim-operator-user'


[[plugins]]
repo = 'itchyny/vim-parenmatch'


[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
set signcolumn=yes
'''


[[plugins]]
repo = 'tpope/vim-fugitive'


[[plugins]]
repo = 'Yggdroot/indentline'
hook_add = '''
let g:indentLine_fileTypeExclude = ['help', 'markdown', 'md']
'''


[[plugins]]
repo = 'tpope/vim-surround'


[[plugins]]
repo = 'LeafCage/foldCC.vim'


[[plugins]]
repo = 'joshdick/onedark.vim'


[[plugins]]
repo = 'w0ng/vim-hybrid'


[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'execute "source" g:vim_dir . "/rc/parts/lightline.rc.vim"'


[[plugins]]
repo = 'prabirshrestha/async.vim'


[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
if executable('pyls')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'pyls',
        \ 'cmd': {server_info->['pyls']},
        \ 'whitelist': ['python'],
        \ })
endif

let g:lsp_signs_enabled = 1
let g:lsp_diagnostics_echo_cursor = 1
let g:lsp_signs_error = {'text': 'X'}
let g:lsp_signs_warning = {'text': '‼'}
let g:lsp_signs_hint = {'text': '?'}
'''


[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'


[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'


