[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'kana/vim-submode'


[[plugins]]
repo = 'kana/vim-operator-user'


[[plugins]]
repo = 'itchyny/vim-parenmatch'


[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
set signcolumn=yes
'''


[[plugins]]
repo = 'tpope/vim-fugitive'


[[plugins]]
repo = 'Yggdroot/indentline'
hook_add = '''
let g:indentLine_fileTypeExclude = ['help', 'markdown', 'md']
'''


[[plugins]]
repo = 'tpope/vim-surround'


[[plugins]]
repo = 'LeafCage/foldCC.vim'


[[plugins]]
repo = 'joshdick/onedark.vim'


[[plugins]]
repo = 'w0ng/vim-hybrid'


[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'execute "source" g:vim_dir . "/rc/parts/lightline.rc.vim"'




