[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'kana/vim-submode'


[[plugins]]
repo = 'kana/vim-operator-user'


[[plugins]]
repo = 'itchyny/vim-parenmatch'


[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'set signcolumn=yes'


[[plugins]]
repo = 'tpope/vim-fugitive'


[[plugins]]
repo = 'Yggdroot/indentline'
hook_add = 'let g:indentLine_fileTypeExclude = ["help", "markdown", "md"]'


[[plugins]]
repo = 'tpope/vim-surround'


[[plugins]]
repo = 'LeafCage/foldCC.vim'


[[plugins]]
repo = 'joshdick/onedark.vim'


[[plugins]]
repo = 'w0ng/vim-hybrid'


[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'execute "source" g:vim_dir . "/rc/parts/lightline.rc.vim"'
# 変数なし「source path」
# 変数あり「execute "source" "path1" . 変数名 . "path2"」(.は連結)


# vim-lsp用
[[plugins]]
repo = 'prabirshrestha/async.vim'


# lazyだと上手く動作しなかった
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
    if executable('pyls')
        au User lsp_setup call lsp#register_server({
            \ 'name': 'pyls',
            \ 'cmd': {server_info->['pyls']},
            \ 'whitelist': ['python'],
            \ })
    endif
    " ----------------------------------------
    noremap [lsp] <Nop>
    nmap <Space>l [lsp]
    noremap <silent> [lsp]l :LspDefinition<CR>
    noremap <silent> [lsp]s :split \| :LspDefinition <CR>
    noremap <silent> [lsp]v :vsplit \| :LspDefinition <CR>
'''

