[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
if = 'has("linux")'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

# [[plugins]]
# repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'itchyny/vim-parenmatch'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Yggdroot/indentline'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'LeafCage/foldCC.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'


# [[plugins]]
# repo = 'xolox/vim-session'
# depends = ['xolox/vim-misc']
# 
# [[plugins]]
# repo = 'xolox/vim-misc'


