" vimrc
" グローバル変数の定義と、rc-loader.vimのロードのみ行う

" windowsでのディレクトリ区切り文字を「/」にする
set shellslash

" このファイル(vimrc)の場所を、g:vim_dirに設定し、以後パスを設定するときはこの環境変数を使用する
" winでは「~/vimfiles」、unixでは「~/.vim」を使用している場合でも、この違いを吸収する
let g:vim_dir = expand('<sfile>:p:h')

" g:vim_dir/rc/rc-loader.vimをロードする
execute 'source ' g:vim_dir . '/rc/rc-loader.vim'
