[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['md', 'markdown']
