[[plugins]]
repo = 'w0rp/ale'
on_ft = ['javascript']

hook_source = '''
    let g:ale_sign_column_always = 1
    let g:ale_linters = { 'javascript': ['eslint']}


    function! AleListToggle()
        " ALEが起動していないときは終了する
        if !exists('g:ale_open_list') | return | endif
        " listが0(off)のときは1(on)にして、1のときは0にする
        if(g:ale_open_list == 0) 
            ALEDisableBuffer  " 一旦aleを終了(ale起動中に変数を変えても反映されないので)
            let g:ale_open_list = 1
            ALEEnableBuffer  " aleを再度起動
        else
            let g:ale_open_list = 0
            " 下のウィンドウに移動してからウィンドウを消す
            execute ":wincmd j"
            execute ":q"
        endif
    endfunction


    nnoremap [ale] <Nop>
    nmap <Space>e [ale]
    nnoremap <silent> [ale]t :call AleListToggle()<CR>
    " エラー間の移動
    call submode#enter_with('alemove', 'n', 'r', '[ale]k', '<Plug>(ale_previous_wrap)')
    call submode#enter_with('alemove', 'n', 'r', '[ale]j', '<Plug>(ale_next_wrap)')
    call submode#map('alemove', 'n', 'r', 'k', '<Plug>(ale_previous_wrap)')
    call submode#map('alemove', 'n', 'r', 'j', '<Plug>(ale_next_wrap)')
'''
