# lazyだと上手く動作しなかった
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
    if executable('pyls')
        au User lsp_setup call lsp#register_server({
            \ 'name': 'pyls',
            \ 'cmd': {server_info->['pyls']},
            \ 'whitelist': ['python'],
            \ })
    endif
    " ----------------------------------------
    noremap [lsp] <Nop>
    nmap <Space>l [lsp]
    noremap <silent> [lsp]l :LspDefinition<CR>
    noremap <silent> [lsp]s :split \| :LspDefinition <CR>
    noremap <silent> [lsp]v :vsplit \| :LspDefinition <CR>

    set omnifunc=lsp#complete
    set signcolumn=yes

    let g:lsp_diagnostics_enabled = 1
    let g:lsp_diagnostics_echo_cursor = 1
    let g:asyncomplete_auto_popup = 1
    let g:asyncomplete_auto_completeopt = 0
    let g:asyncomplete_popup_delay = 200
    let g:lsp_text_edit_enabled = 1
'''
