# lazyだと上手く動作しなかった
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
    if executable('pyls')
        au User lsp_setup call lsp#register_server({
            \ 'name': 'pyls',
            \ 'cmd': {server_info->['pyls']},
            \ 'whitelist': ['python'],
            \ })
    endif
    " ----------------------------------------
    noremap [lsp] <Nop>
    nmap <Space>l [lsp]
    noremap <silent> [lsp]l :LspDefinition<CR>
    noremap <silent> [lsp]s :split \| :LspDefinition <CR>
    noremap <silent> [lsp]v :vsplit \| :LspDefinition <CR>
    " ----------------------------------------
    set omnifunc=lsp#complete
    let g:lsp_diagnostics_enabled = 1 
    let g:lsp_signs_enabled = 1
    let g:lsp_diagnostics_echo_cursor = 1
    let g:lsp_signs_error = {'text': '✗'}
    let g:lsp_signs_warning = {'text': '‼', 'icon': '/path/to/some/icon'}
    let g:lsp_signs_hint = {'icon': '/path/to/some/other/icon'}
'''
