#!/bin/zsh

if [ $# -eq 0 ]; then
    echo " 1              2              3"
    echo "+--------+     +--------+     +--------+"
    echo "|        |     |        |     | |      |"
    echo "|--------|     |--------|     | |------|"
    echo "|    |   |     |  |  |  |     | |  |   |"
    echo "+--------+     +--------+     +--------+"
    echo
    echo " 4              5              6"
    echo "+--------+     +--------+     +--------+"
    echo "| |      |     |      | |     |      | |"
    echo "|--------|     |------| |     |--------|"
    echo "|    |   |     |   |  | |     |   |    |"
    echo "+--------+     +--------+     +--------+"

elif [ $# -eq 1 ]; then

    # +--------+
    # |        |
    # |--------|
    # |    |   |
    # +--------+
    if [ $1 -eq 1 ]; then
        tmux split-window -v -l 22%
        tmux split-window -h -l 40%

    # +--------+
    # |        |
    # |--------|
    # |  |  |  |
    # +--------+
    elif [ $1 -eq 2 ]; then
        tmux split-window -v -l 22%
        tmux split-window -h -l 66%
        tmux split-window -h -l 50%

    # +--------+
    # | |      |
    # | |------|
    # | |  |   |
    # +--------+
    elif [ $1 -eq 3 ]; then
        tmux split-window -h -l 80%
        tmux split-window -v -l 22%
        tmux split-window -h -l 40%

    # +--------+
    # | |      |
    # |--------|
    # |    |   |
    # +--------+
    elif [ $1 -eq 4 ]; then
        tmux split-window -v -l 22%
        tmux select-pane -t 1
        tmux split-window -h -l 80%
        tmux select-pane -t 3
        tmux split-window -h -l 40%

    # +--------+
    # |      | |
    # |------| |
    # |   |  | |
    # +--------+
    elif [ $1 -eq 5 ]; then
        tmux split-window -h -l 20%
        tmux select-pane -t 1
        tmux split-window -v -l 22%
        tmux split-window -h -l 40%

    # +--------+
    # |      | |
    # |--------|
    # |   |    |
    # +--------+
    elif [ $1 -eq 6 ]; then
        tmux split-window -v -l 22%
        tmux select-pane -t 1
        tmux split-window -h -l 20%
        tmux select-pane -t 3
        tmux split-window -h -l 40%
    fi
fi

# tmux split-window -v -p 30
# tmux split-window -h -p 66
# tmux split-window -h -p 50
